server:
  port: 9090
  compression: 
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

db_name : code
db_ip: localhost

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db_ip}:3306/${db_name}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234

#server: 
#    ssl: 
#      key-store: classpath:keystore.p12
#      key-store-password: 38967098gzz
#      keyStoreType: PKCS12
#      keyAlias: jetty
gen:
  project:
    outdir: D:/pro_dir
    datadir: D:/pro_data
    templatedir: D:/pro_temp_data